<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1U6579J" name="com.lc.testngChaoShi.testNG13" tests="1" failures="0" timestamp="14 Dec 2020 13:24:26 GMT" time="5.058" errors="1">
  <testcase name="testNG13_01" time="5.058" classname="com.lc.testngChaoShi.testNG13">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testNG13_01() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testNG13_01() didn't finish within the time-out 5000
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:61)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testNG13_01 -->
</testsuite> <!-- com.lc.testngChaoShi.testNG13 -->
